### ISSUE TITLE
implement a logistic regression based classifier that is trained on the embeddings created by the model trained with contrastive loss.

### ISSUE THREAD

**Issue by Introvertuoso** [Thunfischpirat/SpokenDigits#33]

**Comment by Introvertuoso** [comment]
I need more details to complete this @Thunfischpirat

**Comment by Thunfischpirat** [comment]
Tutorial on which the code was based can be found here https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial17/SimCLR.html
